TechTree/TechTree/TechTree.Presentation.Mvc/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TechTree.Application.Dtos.CategoryDtos;
using TechTree.Application.Services;

namespace TechTree.Presentation.Mvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles ="Admin")]
    public class CategoryController : Controller
    {

        private readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }


        public async Task<IActionResult> Index()
        {
            var result = await _categoryService.GetAll();
            return View(result);
        }

        public async Task<IActionResult>Details(int id)
        {
            var result = await _categoryService.Get(id);
            if(result == null)
            {
                return NotFound();
            }
            return View(result);
        }

        public IActionResult Add()
        {
            return View(new CreateCategoryDto());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>Add(CreateCategoryDto createCategoryDto)
        {
            if(ModelState.IsValid)
            {
                await _categoryService.Add(createCategoryDto);
                return RedirectToAction(nameof(Index));
            }
            return View(createCategoryDto);
        }

        public async Task<IActionResult>Update(int id)
        {
            var category = await _categoryService.Get(id);
            var updateCategoryDto = new UpdateCategoryDto
            {
                Title=category.Title,
                Description=category.Description,
                ThumbnailImagePath=category.ThumbnailImagePath
            };

            return View(updateCategoryDto);
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>Update(UpdateCategoryDto updateCategoryDto)
        {
            if(ModelState.IsValid)
            {
                await _categoryService.Update(updateCategoryDto);
                return RedirectToAction(nameof(Index));
            }
            return View(updateCategoryDto);
        }


        public async Task<IActionResult>Delete(int id)
        {
            if(id==0)
            {
                return NotFound();
            }

            await _categoryService.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> GetItems(int id)
        {
            var items = await _categoryService.GetCategoryWithItems(id);
            return View(items);
        }

    }
}

TechTree/TechTree/TechTree.Presentation.Mvc/Areas/Admin/Controllers/ContentController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TechTree.Application.Dtos.ContentDtos;
using TechTree.Application.Services;

namespace TechTree.Presentation.Mvc.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]

    public class ContentController : Controller
    {
        private readonly IContentService _service;
        private readonly ICategoryItemService _categoryItemService;

        public ContentController(IContentService service, ICategoryItemService categoryItemService)
        {
            _service = service;
            _categoryItemService = categoryItemService;
        }

        public async Task<IActionResult> Index(int Id)
        {
            ViewBag.categoryItemId = Id;
            var content = await _service.GetAll(Id);
            if(content!=null)
            {
                return View(content);

            }
            return RedirectToAction(nameof(Add), new {Id= ViewBag.categoryItemId});
        }

        [HttpGet]
        public IActionResult Add(int Id)
        {
            return View(new CreateContentDto() { CategoryItemId=Id});
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>Add(CreateContentDto createContentDto)
        {
            if(ModelState.IsValid)
            {
                await _service.Add(createContentDto);
                return RedirectToAction(nameof(Index), new { Id = createContentDto.CategoryItemId });
            }
            return View(createContentDto);
        }

        [HttpGet]
        public async Task<IActionResult>Update(int Id)
        {
            var content = await _service.Get(Id);
            var updateContentDto = new UpdateContentDto
            {
                Title=content.Title,
                HTMLContent=content.HTMLContent,
                VideoLink=content.VideoLink,
                CategoryItemId=content.CategoryItemId
            };
            ViewBag.categoryItem = await _categoryItemService.GetAll();
            return View(updateContentDto);
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(UpdateContentDto updateContentDto)
        {
            if(ModelState.IsValid)
            {
                await _service.Update(updateContentDto);
                return RedirectToAction(nameof(Index), new { Id = updateContentDto.CategoryItemId });
            }
            ViewBag.categoryItem = await _categoryItemService.GetAll();
            return View(updateContentDto);

        }

        public async Task<IActionResult>Delete(int Id)
        {
            await _service.Delete(Id);
            return RedirectToAction(nameof(Index), new { Id = ViewBag.categoryItemId });
        }
    }
}

TechTree/TechTree/TechTree.Presentation.Mvc/Areas/Admin/Views/Content/Add.cshtml
@model TechTree.Application.Dtos.ContentDtos.CreateContentDto

<div class="col-12 mt-5">
    <h4>Create Content</h4>
    <form asp-action="Add" method="post" class="w-50 mt-5">
        <div asp-validation-summary="ModelOnly"></div>
        <input type="hidden" asp-for="CategoryItemId" />
        <div class="form-group">
            <label class="form-label">Title</label>
            <input type="text" asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label class="form-label">Video Link</label>
            <input type="text" asp-for="VideoLink" class="form-control" />
            <span asp-validation-for="VideoLink" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label class="form-label">Content</label>
            <textarea asp-for="HTMLContent" rows="5" cols="10" class="form-control"></textarea>
            <span asp-validation-for="HTMLContent" class="text-danger"></span>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary mt-4">Add</button>
        </div>
    </form>
    <div class="form-group mt-3">
        <a asp-action="Index" asp-controller="CategoryItem" asp-route-id="@Model.CategoryItemId" class="link-info text-warning">Back to List</a>
    </div>

</div>

@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}

TechTree/TechTree/TechTree.Presentation.Mvc/Areas/Admin/Views/Content/Index.cshtml
@model IEnumerable<TechTree.Application.Dtos.ContentDtos.ContentsDto>



<div class="row mt-5">
    
    <h4 class="text-center">Contents</h4>
    <div class="mb-3">
            <a asp-action="Add" asp-controller="Content" asp-route-id="@ViewBag.categoryItemId" class="btn btn-primary btn-sm">New Content</a>
            <a asp-action="Index" asp-controller="CategoryItem" asp-route-id="@ViewBag.categoryItemId" class="link-warning m-lg-5">Back to Category Items</a>
    </div>
    
    @foreach (var item in Model)
    {
        <div class="card border-primary mb-3" style="max-width: 100rem;">
            <div class="card-header text-danger"><strong>@item.Title</strong></div>
            <div class="card-body">
                <h6 class="card-title text-primary">Video Link: <span class="text-info">@item.VideoLink</span></h6>
                <hr />
                <p class="card-text text-black">@item.HTMLContent</p>
            </div>
            <div class="mb-3 mt-3">
                <a asp-action="Update" asp-route-id="@item.Id" class="btn btn-warning btn-sm">Update</a>
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger btn-sm">Delete</a>

            </div>
        </div>

    }

</div>

TechTree/TechTree/TechTree.Presentation.Mvc/Areas/Admin/Views/Content/Update.cshtml
@model TechTree.Application.Dtos.ContentDtos.UpdateContentDto

<div class="row mt-5 mb-5">
    <div class="col-md-12 mt-3 m-lg-5">
        <h4 class="align-text-top">Edit @Model.Title Category</h4>
        <form method="post" asp-action="Update" asp-controller="Content" class="w-50 mt-3">
            <div asp-validation-summary="ModelOnly"></div>
            <div class="form-group">
                <label class="form-label">Title</label>
                <input type="text" asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="form-label">Video Link</label>
                <input type="text" asp-for="VideoLink" class="form-control" />
                <span asp-validation-for="VideoLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="form-label">Content</label>
                <textarea asp-for="HTMLContent" class="form-control"></textarea>
                <span asp-validation-for="HTMLContent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label>Category Item</label>
                <select asp-for="CategoryItemId">
                    @foreach (var item in ViewBag.categoryItem)
                    {
                        <option value="">-- Select to Category Item--</option>
                        <option value="@item.Id">@item.Title</option>
                    }
                </select>
            </div>
            <div class="form-group mt-3">
                <button type="submit" class="btn btn-primary">Save the Changes</button>
            </div>
        </form>
        <div class="form-group mt-5">
            <a asp-action="Index" asp-controller="Category" class="link-info text-warning">Back to List</a>
        </div>
    </div>
</div>

@section scripts
{
    <partial name="_ValidationScriptsPartial" />
}