FaturaYonetimSistemi/FaturaYonetimSistemi.Mvc/Areas/Yonetici/Controllers/KullaniciAidatController.cs
using FaturaYonetimSistemi.Services.Abstract;
using FaturaYonetimSistemi.Shared.Dtos.KullaniciAidatDto;
using Microsoft.AspNetCore.Mvc;

namespace FaturaYonetimSistemi.Mvc.Areas.Yonetici.Controllers
{
    [Area("Yonetici")]
    public class KullaniciAidatController : Controller
    {
        private readonly IKullaniciAidatService _kullaniciAidatService;

        public KullaniciAidatController(IKullaniciAidatService kullaniciAidatService)
        {
            _kullaniciAidatService = kullaniciAidatService;
        }

        public IActionResult GetAll(int id)
        {
            var kullaniciAidat = _kullaniciAidatService.GetAllKullaniciAidatlar(id);
            return View(kullaniciAidat);
        }

        public IActionResult Add()
        {
            return View(new InsertKullaniciAidatDto());
        }

        [HttpPost]
        public IActionResult Add(InsertKullaniciAidatDto model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _kullaniciAidatService.AddKullaniciAidat(model);
                    return RedirectToAction("GetAll");
                }
                return View(model);
            }
            catch
            {

                return RedirectToAction("GetAll");
            }
           
        }

        public IActionResult Update(int Id)
        {
            var kullaniciAidat = _kullaniciAidatService.Get(x => x.ID==Id);
            var model = new UpdateKullaniciAidatDto
            {
                KullaniciId=kullaniciAidat.KullaniciId,
                AidatId = kullaniciAidat.AidatId,
                OdendiMi = kullaniciAidat.OdendiMi,
                OdenmeTarihi = kullaniciAidat.OdenmeTarihi,
                AktifMi = kullaniciAidat.AktifMi
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult Update(UpdateKullaniciAidatDto model)
        {
            if(ModelState.IsValid)
            {
                _kullaniciAidatService.UpdateKullaniciAidat(model);
                return RedirectToAction("GetAll");
            }

            return View(model);

        }

        public IActionResult Delete(int id)
        {
            _kullaniciAidatService.SoftDelete(id);
            return RedirectToAction("GetAll");
        }
    }
}

FaturaYonetimSistemi/FaturaYonetimSistemi.Mvc/Areas/Yonetici/Controllers/KullaniciController.cs
using FaturaYonetimSistemi.Services.Abstract;
using FaturaYonetimSistemi.Shared.Dtos.KullaniciDtos;
using FaturaYonetimSistemi.Shared.Entities;
using Microsoft.AspNetCore.Mvc;

namespace FaturaYonetimSistemi.Mvc.Areas.Yonetici.Controllers
{
    [Area("Yonetici")]
    public class KullaniciController : Controller
    {
        private readonly IKullaniciService _kullaniciService;

        public KullaniciController(IKullaniciService kullaniciService)
        {
            _kullaniciService = kullaniciService;
        }

        public IActionResult GetAll()
        {
            var kullanicilar = _kullaniciService.GetAllKullanicilar();
            return View(kullanicilar);
        }

        public IActionResult GetDetail(int id)
        {
            var kullanici = _kullaniciService.GetDetailKullanici(id);
            return View(kullanici);
        }

        public IActionResult Add()
        {
            return View(new InsertKullaniciDto());
        }
        [HttpPost]
        public IActionResult Add(InsertKullaniciDto model)
        {
            if(ModelState.IsValid)
            {
                _kullaniciService.AddKullanici(model);
                return RedirectToAction("GetAll");
            }
            return View(model);
        }

        public IActionResult Update(int id)
        {
            var kullanici = _kullaniciService.Get(x => x.ID == id);
            var model = new UpdateKullaniciDto
            {
                Ad=kullanici.Ad,
                Soyad=kullanici.Soyad,
                TCNo=kullanici.TCNo,
                Fotograf=kullanici.Fotograf,
                Email=kullanici.Email,
                Telefon=kullanici.Telefon,
                Arac=kullanici.Arac,
                Plaka=kullanici.Plaka,
                DaireId=kullanici.DaireId,
                AktifMi=kullanici.AktifMi
            };
            return View(model);
        }
        [HttpPost]
        public IActionResult Update(UpdateKullaniciDto model)
        {
            if(ModelState.IsValid)
            {
                _kullaniciService.UpdateKullanici(model);
                return RedirectToAction("GetAll");
            }
            return View(model);
        }

        public IActionResult Delete(int id)
        {
            _kullaniciService.SoftDelete(id);
            return RedirectToAction("GetAll");
        }

        
    }
}

FaturaYonetimSistemi/FaturaYonetimSistemi.Mvc/Areas/Yonetici/Controllers/KullaniciFaturaController.cs
using FaturaYonetimSistemi.Services.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace FaturaYonetimSistemi.Mvc.Areas.Yonetici.Controllers
{
    [Area("Yonetici")]
    public class KullaniciFaturaController : Controller
    {
        private readonly IKullaniciFaturaService _kullaniciFaturaService;

        public KullaniciFaturaController(IKullaniciFaturaService kullaniciFaturaService)
        {
            _kullaniciFaturaService = kullaniciFaturaService;
        }

        public IActionResult GetAll(int kullaniciId)
        {
            var kullaniciFaturalar = _kullaniciFaturaService.GetAllKullaniciFatura(kullaniciId);
            return View(kullaniciFaturalar);
        }
    }
}

FaturaYonetimSistemi/FaturaYonetimSistemi.Mvc/Controllers/KullaniciController.cs
using FaturaYonetimSistemi.Services.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace FaturaYonetimSistemi.Mvc.Controllers
{
    public class KullaniciController : Controller
    {
        private readonly IKullaniciService _kullaniciService;

        public KullaniciController(IKullaniciService kullaniciService)
        {
            _kullaniciService = kullaniciService;
        }

        public IActionResult Index(int id)
        {
           var kullanici= _kullaniciService.GetDetailKullanici(id);
            return View(kullanici);
        }
    }
}

FaturaYonetimSistemi/FaturaYonetimSistemi.Mvc/Areas/Yonetici/Views/Kullanici/Add.cshtml
@model FaturaYonetimSistemi.Shared.Dtos.KullaniciDtos.InsertKullaniciDto
@using FaturaYonetimSistemi.Shared.Dtos.DaireDtos

<div class="col-md-12">
    <div asp-validation-summary="ModelOnly"></div>
    <form class="w-50" asp-action="Add" asp-controller="Kullanici" method="post" enctype="multipart/form-data">
        <div class="form-group">
            <label>Ad</label>
            <span asp-validation-for="Ad"></span>
            <input type="text" class="form-control" asp-for="Ad" />
        </div>
        <div class="form-group">
            <label>Soyad</label>
            <span asp-validation-for="Soyad"></span>
            <input type="text" class="form-control" asp-for="Soyad" />
        </div>
        <div class="form-group">
            <label>TC Kimlik No</label>
            <span asp-validation-for="TCNo"></span>
            <input type="text" class="form-control" value="" asp-for="TCNo" />
        </div>
        <div class="form-group">
            <label>Fotoğraf Url</label>
            <input type="text" class="form-control" asp-for="Fotograf" />
        </div>
        <div class="form-group">
            <label>Email</label>
            <span asp-validation-for="Email"></span>
            <input type="text" class="form-control" asp-for="Email" />
        </div>
        <div class="form-group">
            <label>Telefon</label>
            <span asp-validation-for="Telefon"></span>
            <input type="text" class="form-control" asp-for="Telefon" />
        </div>
        <div class="form-check">
            <input type="checkbox" class="form-check-input" asp-for="Arac" />
            <label>Araç Var Mı?</label>
        </div>
        <div class="form-group">
            <label>Plaka</label>
            <span asp-validation-for="Plaka"></span>
            <input type="text" class="form-control" asp-for="Plaka" />
        </div>
        <div class="form-group">
            <label>Daire Id</label>
            <span asp-validation-for="DaireId"></span>
            <input type="text" class="form-control" value="" asp-for="DaireId" />
        </div>
        <div class="form-check">
            <input type="checkbox" class="form-check-input" asp-for="AktifMi" />
            <label>Aktif Mi?</label>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-success">Ekle</button>
            <button type="reset" class="btn btn-warning">Temizle</button>
            <a class="btn btn-info" asp-action="GetAll" asp-controller="Kullanici" asp-area="Yonetici">Geri</a>
        </div>
    </form>
</div>

<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

FaturaYonetimSistemi/FaturaYonetimSistemi.Mvc/Areas/Yonetici/Views/Kullanici/GetAll.cshtml
@model List<FaturaYonetimSistemi.Shared.Dtos.KullaniciDtos.ListKullaniciDto>

<div class="col-md-12">
    <a class="btn btn-primary btn-block" asp-action="Add" asp-controller="Kullanici">Yeni</a>
</div>
    <div class="col-md-4 mb-3" style="margin-left:500px;">
        <div class="card" style="width: 20rem;">
            @foreach (var item in Model)
            {
               
                <img class="card-img-top" src="@item.Fotograf" alt="@item.Ad">
                <div class="card-body">
                    <h5 class="card-title">@item.Ad @item.Soyad</h5>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">Daire No: @item.DaireNo</li>
                </ul>
                <div class="card-body">
                    <a class="btn btn-info btn-block" asp-route-id="@item.ID" asp-action="GetDetail" asp-controller="Kullanici">Detay</a>
                    <a class="btn btn-dark btn-block" asp-action="GetAll" asp-controller="KullaniciAidat" asp-route-id="@item.ID">Aidatlar</a>
                    <a class="btn btn-secondary btn-block" asp-action="GetAll" asp-controller="KullaniciFatura" asp-route-id="@item.ID">Faturalar</a>
                </div>
            }

        </div>
    </div>

FaturaYonetimSistemi/FaturaYonetimSistemi.Mvc/Areas/Yonetici/Views/Kullanici/GetDetail.cshtml
@model FaturaYonetimSistemi.Shared.Dtos.KullaniciDtos.DetailKullaniciDto


<div class="card" style="width: 25rem; margin-left:500px">
    <input type="hidden" asp-route="@Model.ID" />

    <img class="card-img-top" src="@Model.Fotograf" alt="Card image cap">
    <div class="card-body">
        <h5 class="card-title">@Model.Ad @Model.Soyad</h5>
        <h5 class="card-title">T.C: @Model.TCNo / @Model.SahibiMi</h5>
        <h5 class="card-title">Kat: @Model.Kat / Daire: @Model.DaireNo / @Model.DaireTipi</h5>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item"><b>Email: </b>@Model.Email</li>
        <li class="list-group-item"><b>Telefon: </b>@Model.Telefon</li>
        <li class="list-group-item"><b>Araç: </b>@Model.Arac</li>
        <li class="list-group-item"><b>Plaka: </b>@Model.Plaka</li>
    </ul>
    <div class="card-body">
        <a class="btn btn-warning btn-block" asp-action="Update" asp-controller="Kullanici" asp-route-id="@Model.ID">Güncelle</a>
        <a class="btn btn-danger btn-block" asp-route-id="@Model.ID" asp-action="Delete">Sil</a>
        <a class="btn btn-info btn-block" asp-action="GetAll" asp-controller="Kullanici">Geri</a>
    </div>
</div>

FaturaYonetimSistemi/FaturaYonetimSistemi.Mvc/Areas/Yonetici/Views/Kullanici/Update.cshtml
@model FaturaYonetimSistemi.Shared.Dtos.KullaniciDtos.UpdateKullaniciDto

<div class="col-md-12">
    <div asp-validation-summary="ModelOnly"></div>
    <form class="w-50" enctype="multipart/form-data" asp-action="Update" asp-controller="Kullanici" method="post">
        <div class="form-group">
            <label>Ad</label>
            <span asp-validation-for="Ad"></span>
            <input type="text" class="form-control" asp-for="Ad" />
        </div>
        <div class="form-group">
            <label>Soyad</label>
            <span asp-validation-for="Soyad"></span>
            <input type="text" class="form-control" asp-for="Soyad" />
        </div>
        <div class="form-group">
            <label>TC Kimlik No</label>
            <span asp-validation-for="TCNo"></span>
            <input type="text" class="form-control" asp-for="TCNo" />
        </div>
        <div class="form-group">
            <label>Fotoğraf Url</label>
            <input type="text" class="form-control" asp-for="Fotograf" />
        </div>
        <div class="form-group">
            <label>Email</label>
            <span asp-validation-for="Email"></span>
            <input type="text" class="form-control" asp-for="Email" />
        </div>
        <div class="form-group">
            <label>Telefon</label>
            <span asp-validation-for="Telefon"></span>
            <input type="text" class="form-control" asp-for="Telefon" />
        </div>
        <div class="form-check">
            <input type="checkbox" class="form-check-input" asp-for="Arac" />
            <label>Araç Var Mı?</label>
        </div>
        <div class="form-group">
            <label>Plaka</label>
            <span asp-validation-for="Plaka"></span>
            <input type="text" class="form-control" asp-for="Plaka" />
        </div>
        <div class="form-group">
            <label>Daire Id</label>
            <span asp-validation-for="DaireId"></span>
            <input type="text" class="form-control" asp-for="DaireId" />
        </div>
        <div class="form-check">
            <input type="checkbox" class="form-check-input" asp-for="AktifMi" />
            <label>Aktif Mi?</label>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-success">Kaydet</button>
            <a class="btn btn-info" asp-action="GetAll" asp-controller="Kullanici" asp-area="Yonetici">Geri</a>
        </div>
    </form>
</div>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>